// Code generated by "stringer -type=LogLevels"; DO NOT EDIT.

package gologger

import (
	"fmt"

	"github.com/rs/zerolog"
)

const _LogLevels_name = "ERRORWARNINFODEBUG"

var _LogLevels_index = [...]uint8{0, 5, 9, 13, 18}

func (i LogLevels) String() string {
	if i >= LogLevels(len(_LogLevels_index)-1) {
		return fmt.Sprintf("LogLevels(%d)", i)
	}
	return _LogLevels_name[_LogLevels_index[i]:_LogLevels_index[i+1]]
}

func SetCustomZerologLevelNames() {
	zerolog.LevelErrorValue = "ERROR"
	zerolog.LevelWarnValue = "WARN"
	zerolog.LevelInfoValue = "INFO"
	zerolog.LevelDebugValue = "DEBUG"
	zerolog.LevelTraceValue = "TRACE"
	zerolog.LevelFatalValue = "FATAL"
}
