// Code generated by "stringer -type=LogLevels"; DO NOT EDIT.

package gologger

import "fmt"

const _LogLevels_name = "ERRORWARNINFODEBUG"

var _LogLevels_index = [...]uint8{0, 5, 9, 13, 18}

func (i LogLevels) String() string {
	if i >= LogLevels(len(_LogLevels_index)-1) {
		return fmt.Sprintf("LogLevels(%d)", i)
	}
	return _LogLevels_name[_LogLevels_index[i]:_LogLevels_index[i+1]]
}
